### PR TITLE
Update vagrant dmg package url

### PR DESCRIPTION
**Pull request by salimane**
cc @jhaals

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Thanks @salimane! I duplicated this in #66 so will close that off and continue on here.

**Comment by jacobbednarz** [comment]
I'm happy to merge this one unless @jhaals has any objections?

**Comment by glarizza** [comment]
Yeah, all the Hashicorp applications seem to be using a new download path - definitely down to see this merged in :+1:

**Comment by jhaals** [comment]
Thanks!

**Comment by salimane** [comment]
@jhaals a new tag release would be appreciated. Thanks!

**Comment by jhaals** [comment]
Released

**Comment by salimane** [comment]
@jhaals thanks :+1:

**Pull request merged**
